### ISSUE TITLE
Update rand_core to 0.6

### ISSUE THREAD

**Issue by kevinlewi** [novifinancial/opaque-ke#101]
From @PaulGrandperrin in #100:

> Also as a small aside, it would be nice if you could wait for rand_core to be released in version 0.6 (rust-random/rand#1072) before releasing your 0.3 version. The new version makes it possible to use rand_core::OsRng on wasm.

We however need to also wait for curve25519-dalek + other dependencies to upgrade their `rand_core` dependency.

cc: @huitseeker

**Comment by PaulGrandperrin** [comment]
Yes, I started opening PRs to some projects:
https://github.com/dalek-cryptography/curve25519-dalek/pull/338
https://github.com/dalek-cryptography/x25519-dalek/pull/64

but first, `rand` 0.8, which syncs traits with `rand_core` 0.6, needs to be released too: https://github.com/rust-random/rand/pull/1076
