### ISSUE TITLE
Allow providing (idU, idS) at ClientLoginFinish phase

### ISSUE THREAD

**Issue by PaulGrandperrin** [novifinancial/opaque-ke#104]
For the same reasons evoked in #100 and in the continuation of #102 , it would be nice to allow providing (idU, idS) at ClientLoginFinish phase.

**Comment by kevinlewi** [comment]
Thanks again for pointing this out -- I forgot to address it in the previous PR. I will roll this out along with some [other changes coming to the envelope construction](https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/102) (which will alter the API slightly)
