### ISSUE TITLE
Provide access to result of CipherSuite::SlowHash::hash()

### ISSUE THREAD

**Issue by PaulGrandperrin** [novifinancial/opaque-ke#105]
I may have a weird use-case, but here it is:
- I want my users to be able to keep some of their data private from the server itself, like their private asymmetric user key
- So, client-side, I want to AEAD this data with a key derived from their password
- So I need the same kind of KDF that is used in `opaque_ke::CipherSuite::SlowHash`
- And instead of calling this expansive KDF twice, it would be nice if I could factorize this computation in some way.
- Also, AFAIK, OPAQUE already takes care of salting the password in a way that prevents precomputation of user-specific rainbow tables, which is a nice property

I feel that I could safely inherit all this nice work done by OPAQUE by using the result of `CipherSuite::SlowHash::hash()` to then derive my user AEAD key.

I am not a cryptographer, does that make sense?

**Comment by kevinlewi** [comment]
Yes, this use-case makes sense, and it sounds like it is a perfect application of the `export_key` parameter, described [here](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-01.html#section-3.4). In this implementation, the `export_key` parameter is populated after calling ClientRegistration's finish and ClientLogin's finish -- guaranteed to be the same byte-string so long as the passwords used during registration and login match.

We should probably have an example usage in the `examples/` directory for this -- will create an issue to track the incorporation of that.

Closing, but feel free to re-open this issue if you have more questions on this / it doesn't satisfy your use-case!

**Comment by PaulGrandperrin** [comment]
Thanks for the tip, that's indeed exactly what I need.
And as far as I understand, I can even use this key directly as it has already been made specific though this function: `export_key = HKDF-Expand(rwdU, concat(nonce, "ExportKey"), Nh)`
