### ISSUE TITLE
Using WithIdentifiers(iud, ids) does not work anymore

### ISSUE THREAD

**Issue by PaulGrandperrin** [novifinancial/opaque-ke#115]
To reproduce:
- verify that `simple_login.s` works correctly: ok
- replace the two lines:
  - `Client(Registration, Login)FinishParameters::default()`
  - by
  - `Client(Registration, Login)FinishParameters::WithIdentifiers(b"idu".to_vec(), b"ids".to_vec())`
- try again to run the code: doesn't work

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: VerificationError(CryptoError(IncompatibleEnvelopeModeError))', examples/simple_login.rs:118:6
```

This feature was working at https://github.com/novifinancial/opaque-ke/commit/f5b5391ee0365263556cc44cb31a8fbe5a787d9e

**Comment by kevinlewi** [comment]
When supplying custom identifiers, there are three places where you need to supply them consistently:
- client registration finish parameters
- server login start parameters
- client login finish parameters

Failing to supply the same pair of custom identifiers in any of the three steps above will result in an error -- see
https://github.com/novifinancial/opaque-ke/blob/master/src/lib.rs#L717-L718

I think you forgot to do the server login start parameters. Closing this issue but feel free to re-open if this wasn't addressed!

**Comment by kevinlewi** [comment]
(It is likely the case that in the past, when the identifiers were not supplied to server login start, the protocol would still complete successfully. But that is supposed to be incorrect behavior and should no longer be the case...)

**Comment by PaulGrandperrin** [comment]
You guessed exactly what happened, thanks for your help!
