### ISSUE TITLE
Example can not run

### ISSUE THREAD

**Issue by MountainLovers** [novifinancial/opaque-ke#147]
Version: v0.3.1
Rust: rustc 1.50.0 (cb75ad5db 2021-02-10)
There are some Serialization/Deserialization errors.

> error[E0599]: no method named `serialize` found for struct `ServerRegistration<Default>` in the current scope
  --> src/main.rs:86:19
   |
86 |     password_file.serialize()
   |                   ^^^^^^^^^ method not found in `ServerRegistration<Default>`
error[E0599]: no function or associated item named `deserialize` found for struct `ServerRegistration<Default>` in the current scope
   --> src/main.rs:106:56
    |
106 |     let password_file = ServerRegistration::<Default>::deserialize(password_file_bytes).unwrap();
    |                                                        ^^^^^^^^^^^ function or associated item not found in `ServerRegistration<Default>`

**Comment by MountainLovers** [comment]
FIX: I see commits #138 . I change back to the 'to_bytes()' in line 86 and 'try_from' in 106. It works.

**Comment by kevinlewi** [comment]
Hi, sorry about this and thanks for the catch! I thought I had fixed the tests to catch compilation errors in the examples/ directory, but it appears that that was not the case. Will put out a PR soon.

**Comment by kevinlewi** [comment]
Oh, I see, it seems like you pulled the example from master (not the v0.3.1 version), which means that there is nothing to fix here. Will be releasing a v0.4 soon hopefully which should include the updated API (serialize() / deserialize()).

Closing, but feel free to re-open if you encounter this again!
