### ISSUE TITLE
Fake CredentialResponse for Account Enumeration

### ISSUE THREAD

**Issue by jordanisaacs** [novifinancial/opaque-ke#164]
In the draft OPAQUE proposal, to prevent account enumeration attacks during authentication the server is supposed to respond with a fake CredentialResponse (see [here](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#create-credential-response)). I may have missed it, but I did not see anything in the docs for creating this fake CredentialResponse. Is this implemented and/or is there an example of creating a fake CredentialResponse?

**Comment by kevinlewi** [comment]
Hi @jordanisaacs, you are right in that support for the "fake CredentialResponse" is not in this implementation yet. This implementation is synced with https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-03.html (version 03) of the draft OPAQUE proposal, which did not include the fake CredentialResponse yet.

It was however introduced in version 05 (https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-05.html), and I am currently in the process of extending the API to support it, which should align with the v0.6 release of opaque-ke.

Hope that answers your question! I will keep this issue open until it is implemented.

**Comment by kevinlewi** [comment]
Implemented in https://github.com/novifinancial/opaque-ke/pull/178
