### ISSUE TITLE
Argon2 support

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#179]
Right now only support for scrypt is implemented. Is Argon2 support in scope of this project?

I have an implementation ready that is based on https://crates.io/crates/argon2, I was wondering what I should PR against, `master` or `0.6`?

**Comment by kevinlewi** [comment]
Sure, feel free to PR against `master` (I will be merging them soon anyway)! scrypt support is gated behind a feature, and it seems like argon2 support should also be behind a feature as well.
