### ISSUE TITLE
Expose SIMD feature

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#187]
curve25519-dalek [exposes a SIMD feature](https://github.com/dalek-cryptography/curve25519-dalek/blob/3e189820da03cc034f5fa143fc7b2ccb21fffa5e/Cargo.toml#L51) (nightly only), is it in scope for opaque-ke to re-expose this? 

Alternatively, of course, consumers can just activate this feature themselves by adding curve25519-dalek as a dependency in their crate.

**Comment by kevinlewi** [comment]
Hmm, no strong opinions about re-exposing this versus not. It seems like applications which would like to take advantage of the SIMD feature would need to add curve25519-dalek as a dependency (in which case they could just turn on the feature themselves) anyway, so I am leaning towards not re-exposing this.

But if you have a specific use-case in mind that would benefit, would love to hear it!

**Comment by daxpedda** [comment]
There is no specific use-case in mind, I consider it a good practice is all:
- clearer dependency tree
- less duplication (update has to happen in only one dependency)

As you can see, this is a very shallow and subjective list :laughing:.

**Comment by kevinlewi** [comment]
Fair enough -- looking forward to the PR!

**Comment by daxpedda** [comment]
I guess this should be done at a later point, the feature is currently broken:
https://github.com/dalek-cryptography/subtle/pull/85

**Comment by kevinlewi** [comment]
Closing for now, in that case
