### ISSUE TITLE
Preparing for a v0.6 release

### ISSUE THREAD

**Issue by kevinlewi** [novifinancial/opaque-ke#189]
I'd like to cut a release for v0.6 soon -- say, by the end of this week (June 25). Are there any changes that anyone would like to get in before the cut?

The last version (v0.5) was released on March 1, 2021, and since then:

- The draft spec was updated twice (v0.5 was synced with draft-irtf-cfrg-opaque-03, and the latest is now draft-irtf-cfrg-opaque-05 which we are synced with)
- Various security improvements: (https://github.com/novifinancial/opaque-ke/commit/98f1821897cd2800e5bffb2a70541056145e99cc), (https://github.com/novifinancial/opaque-ke/commit/468e0690d7f2ae91c9a55474fcf40b0457519385), (https://github.com/novifinancial/opaque-ke/commit/940d1dcdb29e9de45a5123adab578b3446502b72)
- Serde support behind a feature
- Supporting common traits (https://github.com/novifinancial/opaque-ke/commit/eb59676a940b15f77871aefe1e46d7b5bf85f40a)
- Swapping out scrypt for argon2 (https://github.com/novifinancial/opaque-ke/commit/535b9b8ee41392c2a0c100f71f5cd04497a61817)

**Comment by daxpedda** [comment]
#191 and #193 are the last ones we need.

**Comment by kevinlewi** [comment]
FYI: I will likely be delaying this release until after the holidays, unless there is an urgent need for publishing earlier.

**Comment by daxpedda** [comment]
I'm not sure what holidays, but we do "need" a release before the 10th of July. I already planned to release a fork on crates.io, but I prefer not to.

On the other hand it's no problem, releasing a fork is a viable option :slightly_smiling_face:.

**Comment by kevinlewi** [comment]
Ah, sorry -- I was referring to July 4th as the holidays. Anyway, given your restraints, I will aim publish the next version tomorrow, after some small updates to the changelog and documentation. Thanks for the feedback!

**Comment by kevinlewi** [comment]
Published
