### ISSUE TITLE
`Group` implementation support

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#198]
I have done some work towards implementing P256 support in opaque-ke. In this process I discovered some potential shortcomings in some of the interfaces:
- `PublicKey` and `PrivateKey` are currently fixed to be 32-bytes, which doesn't apply to other prime-order groups, like P256
- [p256's `Scalar` implementation](https://docs.rs/p256/0.9.0/p256/struct.Scalar.html) for example, doesn't support returning a reference to it's underlying memory, but currently `Group::scalar_as_bytes` requires this, I figured that `Group::Scalar` might just implement `Copy` to solve this issue, which might be reasonable?
- `expand_message_xmd` is currently not exposed, which makes sense, but I understand if opaque-ke expects implementors to bring their own implementation
- testing, for example the test vectors given in the RFC, is hard to impossible from outside the crate

I'm not actually suggesting opaque-ke to provide a P256 implementation, though I don't mind if it does and I'm willing to provide the PR. But it seems that the current provided interface has to be improved either way to make implementations work.

**Comment by kevinlewi** [comment]
p256 support would be great to have. One major hitch that I ran into awhile back when considering adding p256 was a lack of a hash-to-curve implementation. It looks like https://github.com/RustCrypto/traits/issues/481 has had some updates since then -- perhaps we could fully support it now?

The shortcomings you enumerated for the interfaces + their proposed fixes generally sound good to me.

**Comment by daxpedda** [comment]
> p256 support would be great to have.

I'm happy to upstream, but I must admit that I'm not entirely confident in what I'm doing, I'm not a cryptographer after all.

> One major hitch that I ran into awhile back when considering adding p256 was a lack of a hash-to-curve implementation. It looks like [RustCrypto/traits#481](https://github.com/RustCrypto/traits/issues/481) has had some updates since then -- perhaps we could fully support it now?

If you can help me understand the problem here, `Group` has a function called `hash_to_curve`:
https://github.com/novifinancial/opaque-ke/blob/349329cdebf35bbb3767413ea8905aa4ababbf02/src/group.rs#L131-L139
I don't entirely understand what `RistrettoPoint::from_uniform_bytes`, but it doesn't seem like hash to curve to me.
But you use `expand_message_xmd` here:
https://github.com/novifinancial/opaque-ke/blob/349329cdebf35bbb3767413ea8905aa4ababbf02/src/map_to_curve.rs#L43-L62
Can the same `expand_message_xmd` not be used for P256 here?

This is my current solution:
https://github.com/khonsulabs/custodian/blob/be0fad7d92340a9d6ee026de6313d9ed167625c0/password/src/cipher_suite/p256.rs
Upstreaming would also allow us to properly test against the provided test vectors of the RFC to confirm everything's right.

**Comment by kevinlewi** [comment]
> I don't entirely understand what RistrettoPoint::from_uniform_bytes does, but it doesn't seem like hash to curve to me.

It is indeed the Ristretto hash-to-curve implementation :)

> Can the same expand_message_xmd not be used for P256?

It definitely can. At the time, I did not see a way to do an RFC-compliant hash-to-curve from P256, but it looks like your implementation could work (paired with expand_message_xmd). Or maybe the best alternative would be to just rely on the hash2field crate (which also implements expand_message_xmd I think).
