### ISSUE TITLE
`CipherSuite` AKE and OPRF

### ISSUE THREAD

**Issue by daxpedda** [novifinancial/opaque-ke#218]
In light of discussions in #213 and cfrg/draft-irtf-cfrg-opaque#238 I propose the following:
- Merge `Group` and `GroupWithMapToCurve`
- Add a new associated type to `CipherSuite`: OPRF

The goal is to decouple AKE from OPRF to allow for example X25519 for AKE and ristretto255 for Ristretto.

**Comment by kevinlewi** [comment]
Resolved in #222
