### ISSUE TITLE
P256's `is_square` bug

### ISSUE THREAD

**Issue by Sc00bz** [novifinancial/opaque-ke#238]
This is just checking if `result.number` is one twice and might leak timing. Assuming it's not optimized out which I feel like it would be.

https://github.com/novifinancial/opaque-ke/blob/d1dfee9a6545d7dfddc6dd94f985f31b3221c54e/src/group/p256.rs#L308-L320

Line 319 should be something like this:
```
result.number.is_zero() || result.number.is_one()
```
But this also leaks the timing of whether `self.number` is zero which really doesn't matter too much. Note testing `is_one` first will leak the timing of whether `self.number` is a non-zero square which is way worse. The correct fix is a function that tests for zero or one. It would work by converting it to bytes then masking out the lowest bit and checking if it's zero. Unless you have a constant time less than compare function. Also that `is_zero` function is no longer used.

**Comment by daxpedda** [comment]
Thank you, hopefully we will be able to replace most of this sooner then later. `is_zero` is used below, I don't know why `is_zero` uses `is_one`, that's wrong anyway, so I had to correct that.

**Comment by Sc00bz** [comment]
Oh I thought https://github.com/novifinancial/opaque-ke/blob/65a0c2f98d592bd820a14900266cf909f7add949/src/group/p256.rs#L357 was a different `is_zero`, but I am a rust noob and made a lot of assumptions on what is going on.
