### ISSUE TITLE
Remove unwrap from public_key() function

### ISSUE THREAD

**Issue by kevinlewi** [novifinancial/opaque-ke#256]
These `unwrap`s have to be removed.

My idea was to use the appropriate `SecretKey` type instead of storing `GenericArray`s everywhere. I believe this would be better anyway, because conversion isn't free (it's very cheap though) and any checking is now guaranteed in the type and can now be handled during serialization and creation.

_Originally posted by @daxpedda in https://github.com/novifinancial/opaque-ke/pull/250#r773146032_

**Comment by daxpedda** [comment]
RustCrypto/utils#652 is a problem we will have to circumvent if we want to use these types.
