### ISSUE TITLE
Update draft references to draft-irtf-cfrg-opaque-08

### ISSUE THREAD

**Issue by kevinlewi** [novifinancial/opaque-ke#259]
A bunch of places (docs, README) still reference "draft-irtf-cfrg-opaque-05", which should be updated to the latest on https://datatracker.ietf.org/doc/draft-irtf-cfrg-opaque/, which is version 08.

**Comment by Erik1000** [comment]
Just wanna note that it's [version 8](https://datatracker.ietf.org/doc/draft-irtf-cfrg-opaque/08/) since march 7th.

**Comment by kevinlewi** [comment]
Closed by #271
