### ISSUE TITLE
Can't compile 0.6.0 version referenced in opaque-wasm, can you please help?

### ISSUE THREAD

**Issue by jaroslavsaxa** [novifinancial/opaque-ke#264]
trying to build opaque-wasm which refers opaque-ke 0.6.0
following error:

Compiling opaque-ke v0.6.0

--> opaque-ke-0.6.0/src/envelope.rs:64:17
   |
64 | #[derive(Clone, Copy, Debug, Eq, Hash, PartialEq, Zeroize)]
   |                 ^^^^ Copy not allowed on types with destructors
   |
   = note: this error originates in the derive macro `Copy` (in Nightly builds, run with -Z macro-backtrace for more info)

For more information about this error, try `rustc --explain E0184`.
error: could not compile `opaque-ke` due to previous error

rust version: 1.58.1

**Comment by kevinlewi** [comment]
See https://github.com/novifinancial/opaque-ke/pull/237 (and https://github.com/iqlusioninc/crates/issues/876)

This fix is to essentially move off of zeroize v1.1... which was pinned opaque-ke v0.6.0 unfortunately. Would it be possible to override the zeroize dependency to beyond v1.1 for now, until we release a new version of opaque-ke (and opaque-wasm also updates)?

**Comment by daxpedda** [comment]
I think the issue here is that @jaroslavsaxa is actually using the new `zeroize`/`zeroize_derive` version, which is fixed and actually implements `Drop`, the compilation then fails because `Copy` is implemented on our type, which isn't allowed.

Further, all versions of `zeroize_derive`, the package that actually had the issue, before that fix were yanked, so `cargo update -p zeroize_derive --precise 1.1.0` doesn't work.

@kevinlewi I think an easy fix would be to backport this fix and release a `0.6.1`?

**Comment by daxpedda** [comment]
@kevinlewi I made a fix here: https://github.com/novifinancial/opaque-ke/compare/v0.6.0...khonsulabs:v0.6.1?expand=1
If you make a branch based on v0.6.0 I can PR against it.

**Comment by kevinlewi** [comment]
I discussed offline (through email) with @jaroslavsaxa -- it seems like his problems were addressed since he could modify a local copy of opaque-ke for his purposes... so we can probably close this and forego doing a new release... for now.

**Comment by jaroslavsaxa** [comment]
Hi Friends, will be version 0.6.1 published to crates.io so we can refererence it in opaque-wasm?

**Comment by kevinlewi** [comment]
Thanks @daxpedda, just created a v0.6 branch, let's release a v0.6.1 to fix this issue.

**Comment by daxpedda** [comment]
> Releasing a 0.6.1 won't address the issue with opaque-wasm depending on opaque-ke 0.6.0 because of this line: https://github.com/marucjmar/opaque-wasm/blob/master/Cargo.toml#L18 unfortunately.

`cargo update` should take care of it, but considering it's broken, I would recommend yanking it, which would fix the problem automatically.

**Comment by kevinlewi** [comment]
Yanked 0.6.0 and released 0.6.1.
