### ISSUE TITLE
question: opaque-ke 1.2.0 refers to which version  of draft-irtf-cfrg-opaqu?

### ISSUE THREAD

**Issue by jaroslavsaxa** [novifinancial/opaque-ke#265]
opaque-ke  0.6.0 refers to draft-irtf-cfrg-opaque-05
opaque-ke 1.2.0 refuse to draft-irtf-cfrg-opaque-03 - really or it's just typo and in reality it's draft-irtf-cfrg-opaque-07+?

**Comment by kevinlewi** [comment]
1.2.0 refers to version 03, it is not a typo.

The current main branch refers to  draft-irtf-cfrg-opaque-07
