### ISSUE TITLE
Offer options for keying the protocol by user identity

### ISSUE THREAD

**Issue by huitseeker** [novifinancial/opaque-ke#31]
Most, if not all initial messages in the Draft RFC are keyed by a user identity (IdU). We do not have such a concept represented in any of our protocol.

We can either:
1. Choose to add the identity to the concerned functions, modifying our actual methods.
2. Have an overlay API that calls into our (therefore backend) methods, and that are keyed by identity.

In both cases, we will need an `IdU` to put into the message representation.

**Comment by kevinlewi** [comment]
Addressed in #56
