### ISSUE TITLE
Finish Serialization roundtrips

### ISSUE THREAD

**Issue by huitseeker** [novifinancial/opaque-ke#32]
We have `TryFrom` and `ToBytes` implementation tests for a number of messages, tested in 
https://github.com/novifinancial/opaque-ke/blob/master/src/tests/serialization.rs

Yet those roundtrip tests are limited to a few message formats, which essentially end after `LoginRequest`. This task aims at completing them.

**Comment by kevinlewi** [comment]
This has been completed awhile ago.
