### ISSUE TITLE
What is the pepper?

### ISSUE THREAD

**Issue by louisabraham** [novifinancial/opaque-ke#39]
I understand it as a pun over a salt, but how is it meant to be used? Can the user ID be used for example?

From the code, it looks it's only used in the map_to_curve construction in the first step of OPRF.

It's  related to #37, the pepper probably being used to mitigate the risk of rejection sampling for Edwards curves, am I wrong?

**Comment by kevinlewi** [comment]
The pepper is meant to be a client-side salt, see https://en.wikipedia.org/wiki/Pepper_(cryptography).

We can think of the password file as a storage of the value `OPRF(salt, password)` -- adding the pepper means that we are essentially storing `OPRF(salt, HKDF(password, pepper))`, in an effort to increase the entropy of the password file if the client is able to retain the pepper at login time.

A user ID can certainly be used for the pepper. Ideally, we would want to use a string with the maximum amount of entropy that can be kept consistent between user registration and login.
