### ISSUE TITLE
Make "hash" module public

### ISSUE THREAD

**Issue by tomvardasca** [novifinancial/opaque-ke#63]
Hi,

Congrats for this great library!
Is it possible to make the `hash` module public? 
I already implemented my slow hash with Argon2 and do not wan't to use a forked version of this library.

Kind Regards,
Tomé

**Comment by kevinlewi** [comment]
@tomvardasca If you can verify that this is the fix you were looking for, then I'd be happy to patch and release v0.2.1 with this change. Thanks!

**Comment by tomvardasca** [comment]
That was exactly was I was looking for 😄 
Thanks a lot for changing this so quickly.
