### ISSUE TITLE
32bit support?

### ISSUE THREAD

**Issue by 0x6273** [novifinancial/opaque-ke#82]
HI, I would like to use this library with `wasm32-unknown-unknown` target. But this library seems to assume `usize` is always 64 bits, which leads to errors when compiling on 32bit targets.

https://github.com/novifinancial/opaque-ke/blob/697cd7a788c5cd9812a02ae16fcc3256aa51af11/src/serialization/mod.rs#L95-L99

**Comment by kevinlewi** [comment]
Thanks for pointing this out! This is in the process of being addressed (#81 for starters) -- will update here once it's fixed.

**Comment by kevinlewi** [comment]
Closing as this has been resolved in #80 which has been merged to master. Please re-open if you are still encountering an issue here.
