### ISSUE TITLE
Have a structured `Serialization/Deserialization` error

### ISSUE THREAD

**Issue by huitseeker** [novifinancial/opaque-ke#89]
In the current 0.3.0 pre-release, we have more complex serialization / deserialization routines. Here are some of the issues we would like to diagnose at the developer level, yet not expose to the user:

- length mismatches between described length and observed length in deserialization,
- u64::MAX >= token size > u32::MAX
- ...

Ideally, we would do this with a `Serialize` / `Deserialize` structured Error type, which wraps into `PakeError`, rather than percolate such errors at the level of `PakeError` like #85 does (through using (de)serialize function)

**Comment by kevinlewi** [comment]
Closing as this is not super relevant / necessary anymore
